### ISSUE TITLE
[FEATURE REQUEST] Add Tennis activity and gear

### ISSUE THREAD

**Issue by tinchodin** [joaovitoriasilva/endurain#112]
Add Tennis activity and Rackets to the gear combo.

**Comment by joaovitoriasilva** [comment]
Can I ask you to send me some .fit/.gpx files with tennis activities so I can check them out and add support? joao@endurain.com

Thank you

**Comment by rgmelkor** [comment]
> Can I ask you to send me some .fit/.gpx files with tennis activities so I can check them out and add support? [joao@endurain.com](mailto:joao@endurain.com)
> 
> Thank you

Sent!

**Comment by joaovitoriasilva** [comment]
Thank you.
Should be implemented on v0.10.0

**Comment by rgmelkor** [comment]
Awesome! thanks a lot! also, it would be nice (i dont know if it actually
happens) but the top 3 is dinamic? or is fixed on those 3 activities?

**Comment by rgmelkor** [comment]
Yes, exactly that, as i dont run or swim, it would be nice if tennis appears, but its not based on distance, maybe if we can chose between calories and distance?
I do bike (but much more casual than normal people i think) and for me, visualizing calories is more satisfying haha.

**Comment by rgmelkor** [comment]
Hi, sorry to bother you again, im loving endurain! do u have any ETA for
v0.10 ?

**Comment by joaovitoriasilva** [comment]
Hello, no problem :)
Next week. I will finish what is missing today or tomorrow (I hope), but then easter is Sunday, and my availability to fix any issue in the weekend might be low. That's why I am pushing it to next week.

I released a beta/dev release "dev_13042025" that already supports what you asked. If you are feeling lucky you can try it out and give me some feedback :) If you do it, backup your DB prior to it ;)

**Comment by rgmelkor** [comment]
m... I dont see any changes, version above still shows v0.9.3 and cant see
tennis activity or spanish as language. Im using docker and pulled
ghcr.io/joaovitoriasilva/endurain:dev_13042025

**Comment by rgmelkor** [comment]
dont listen to me, maybe was a cache thing, i now see the changes.

**Comment by joaovitoriasilva** [comment]
Do several refreshes and try it in a private windows pls. Should be a cache thing

**Comment by tinchodin** [comment]
Solved in dev_13042025
