### ISSUE TITLE
[BUG]: Garmin Connect does not work after some days

### ISSUE THREAD

**Issue by loberhauser** [joaovitoriasilva/endurain#178]
## Checklist

- [x] I have searched **existing issues** to make sure this bug hasn't already been reported.
- [x] I have checked the **documentation** at [https://docs.endurain.com](https://docs.endurain.com) and didn't find a solution.

## Description

The moment I connect garmin with endurain everything works and all my activities are displayed. After some days (have not tested how many days exactly) the integration does no longer work. Every request to the endurain api responds with a positive feedback but I can't figure out what the problem is because there are no logs for the background tasks.

## Steps to Reproduce

1. Version v0.11.3
2. Connect endurain with garmin connect
3. Wait some days (3-4)
4. Sync activities
5. No new activities are shown

What did you expect to happen?
New activities.

**Comment by loberhauser** [comment]
Badly I reconnected the Garmin integration so I haven't any new logs. I took a look on older logs but can't find any errors only infos and it seems endurain also checks for new activities but does not find new ones. I will take a closer look the next coming days after I do my exercises.

**Comment by Flyingfufu** [comment]
Hello. Thanks for this nice container !

Same issue here. Had a look in my logs, an no error nor failure message appear. 
```INFO:     172.29.20.3:59292 - "GET /api/v1/garminconnect/activities?start_date=2025-05-22&end_date=2025-05-29 HTTP/1.1" 202 Accepted
INFO:     127.0.0.1:35996 - "GET /api/v1/about HTTP/1.1" 200 OK
INFO:     172.29.20.3:59800 - "GET /settings HTTP/1.1" 200 OK
INFO:     connection closed
INFO:     172.29.20.3:59964 - "GET /settings HTTP/1.1" 200 OK
INFO:     ('172.29.20.3', 59974) - "WebSocket /api/v1/ws/1" [accepted]
INFO:     connection open
INFO:     172.29.20.3:59984 - "GET /api/v1/public/server_settings HTTP/1.1" 200 OK
INFO:     172.29.20.3:60004 - "GET /api/v1/users/number HTTP/1.1" 200 OK
INFO:     172.29.20.3:59994 - "GET /api/v1/users/page_number/1/num_records/5 HTTP/1.1" 200 OK
INFO:     172.29.20.3:60014 - "GET /api/v1/sessions/user/1 HTTP/1.1" 200 OK
INFO:     172.29.20.3:60100 - "GET /sw.js HTTP/1.1" 200 OK
INFO:     172.29.20.3:60110 - "GET /workbox-1ea6f077.js HTTP/1.1" 200 OK
INFO:     127.0.0.1:36704 - "GET /api/v1/about HTTP/1.1" 200 OK```

Hope this will help to troubleshoot the issue

**Comment by joaovitoriasilva** [comment]
Can any of you look to app.log and see if there is any error? Thanks

**Comment by loberhauser** [comment]
Sorry cut out most of the error:
`2025-05-28 23:31:59,364 - main_logger - ERROR - Error fetching activities for user 1 between 2025-05-21 and 2025-05-28: 'expires_in'
Traceback (most recent call last):
  File "/app/backend/garmin/activity_utils.py", line 30, in fetch_and_process_activities_by_dates
    garmin_activities = garminconnect_client.get_activities_by_date(
        start_date.date(), end_date.date()
    )
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 1151, in get_activities_by_date
    act = self.connectapi(url, params=params)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 218, in connectapi
    return self.garth.connectapi(path, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 184, in connectapi
    resp = self.request(method, "connectapi", path, api=True, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 133, in request
    self.refresh_oauth2()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 179, in refresh_oauth2
    self.oauth2_token = sso.exchange(self.oauth1_token, self)
                        ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 199, in exchange
    return OAuth2Token(**set_expirations(token))
                         ~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 225, in set_expirations
    token["expires_at"] = int(time.time() + token["expires_in"])
                                            ~~~~~^^^^^^^^^^^^^^
KeyError: 'expires_in'`

**Comment by Flyingfufu** [comment]
here is mine (similar) 

```2025-05-29 19:04:13,832 - main_logger - INFO - User 1: 0 Garmin Connect body composition processed
2025-05-29 19:04:13,833 - apscheduler.executors.default - INFO - Job "retrieve_garminconnect_users_bc_for_days (trigger: interval[4:00:00], next run at: 2025-05-29 23:04:13 CEST)" executed successfully
2025-05-29 20:04:13,085 - apscheduler.executors.default - INFO - Running job "refresh_strava_tokens (trigger: interval[1:00:00], next run at: 2025-05-29 21:04:13 CEST)" (scheduled at 2025-05-29 20:04:13.083654+02:00)
2025-05-29 20:04:13,085 - apscheduler.executors.default - INFO - Running job "retrieve_strava_users_activities_for_days (trigger: interval[1:00:00], next run at: 2025-05-29 21:04:13 CEST)" (scheduled at 2025-05-29 20:04:13.084019+02:00)
2025-05-29 20:04:13,085 - apscheduler.executors.default - INFO - Running job "retrieve_garminconnect_users_activities_for_days (trigger: interval[1:00:00], next run at: 2025-05-29 21:04:13 CEST)" (scheduled at 2025-05-29 20:04:13.084316+02:00)
2025-05-29 20:04:13,089 - main_logger - INFO - User 1: No Strava token found. Will skip processing
2025-05-29 20:04:13,090 - apscheduler.executors.default - INFO - Job "refresh_strava_tokens (trigger: interval[1:00:00], next run at: 2025-05-29 21:04:13 CEST)" executed successfully
2025-05-29 20:04:13,090 - main_logger - INFO - User 1: Strava not linked
2025-05-29 20:04:13,091 - apscheduler.executors.default - INFO - Job "retrieve_strava_users_activities_for_days (trigger: interval[1:00:00], next run at: 2025-05-29 21:04:13 CEST)" executed successfully
2025-05-29 20:04:13,712 - main_logger - ERROR - Error fetching activities for user 1 between 2025-05-28 and 2025-05-29: 'expires_in'
Traceback (most recent call last):
  File "/app/backend/garmin/activity_utils.py", line 30, in fetch_and_process_activities_by_dates
    garmin_activities = garminconnect_client.get_activities_by_date(
        start_date.date(), end_date.date()
    )
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 1151, in get_activities_by_date
    act = self.connectapi(url, params=params)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 218, in connectapi
    return self.garth.connectapi(path, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 184, in connectapi
    resp = self.request(method, "connectapi", path, api=True, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 133, in request
    self.refresh_oauth2()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 179, in refresh_oauth2
    self.oauth2_token = sso.exchange(self.oauth1_token, self)
                        ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 199, in exchange
    return OAuth2Token(**set_expirations(token))
                         ~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 225, in set_expirations
    token["expires_at"] = int(time.time() + token["expires_in"])
                                            ~~~~~^^^^^^^^^^^^^^
KeyError: 'expires_in'
2025-05-29 20:04:13,714 - main_logger - INFO - User 1: Started Garmin Connect activities processing for date range 2025-05-28 to 2025-05-29
2025-05-29 20:04:13,714 - main_logger - INFO - User 1: 0 Garmin Connect activities processed
2025-05-29 20:04:13,714 - apscheduler.executors.default - INFO - Job "retrieve_garminconnect_users_activities_for_days (trigger: interval[1:00:00], next run at: 2025-05-29 21:04:13 CEST)" executed successfully
```

**Comment by matin** [comment]
Garth maintainer here

@Flyingfufu could you print the value of `token` (with your creds masked)? I want to see what's returned to see what the issue is and see if there's a way Garth can address it

**Comment by joaovitoriasilva** [comment]
@matin thanks for reaching out! Just curious are you using Endurain? :) 

I will later today release a dev image that prints this

**Comment by joaovitoriasilva** [comment]
Hello, a new dev version is available (dev_02062025) that prints the tokens to the console. @maksm, @loberhauser and @Flyingfufu can you kindly test with this version and report the error plus the information requested by @matin?

Serializing tokens (which happens on link) prints tokens in clear text. Deserializing tokens (which happens in every retrieval) prints tokens encrypted.

Bellow an example of mine, however I don't have this problem and can't reproduce it.

```
Deserializing OAuth1 token. Tokens should be encrypted.
{'oauth_token': 'gAAAAABoLfjM-j22xNpqppeC4l0_9e4_4NdmYckI9EsLom91DwsJE05xIkUwXOWHQcrOtHdP0XrLMxq-jlV1dOzFMCf146CnhjAHBNvUXQ-HUC0KkuHsOnM_YXrDqdUaJa__GymlbPk0', 'oauth_token_secret': 'gAAAAABoLfjMRYgqCAJPSIxLyb-g5UbzFw3yb4elg7IicegIcwXTfCxUp9qzQ8Yliy29BzjPNJdMRtPzDOhW6rdtS2sy4Ess5h7RctB2IRfZo61x9oJ9c772KQH1p9On9viaJV7z3yj3', 'mfa_token': 'gAAAAABoLfjMQzn9qNOakvGnNyTASDRtFzADQ4TgL51FCu9G0Hh8Dl1dcTJNQI1PmhlPgibV-XNaAPGRBWojqWQVkQHVgkfkLdrTFJ8slqTczN7hJr2pKWG3MZ3EzhvULf29FURbE75TLNlI-09wjFORBUdhlem0plCDws8-pN6dBwUKeJzHsYg=', 'mfa_expiration_timestamp': '2026-05-21T16:01:13', 'domain': 'garmin.com'}

Deserializing OAuth2 token. Tokens should be encrypted.
{'scope': 'COMMUNITY_COURSE_READ GARMINPAY_WRITE GOLF_API_READ ATP_READ GHS_SAMD GHS_UPLOAD INSIGHTS_READ DIVE_API_READ COMMUNITY_COURSE_WRITE CONNECT_WRITE GCOFFER_WRITE DI_OAUTH_2_AUTHORIZATION_CODE_CREATE GARMINPAY_READ DT_CLIENT_ANALYTICS_WRITE GOLF_API_WRITE INSIGHTS_WRITE PRODUCT_SEARCH_READ OMT_CAMPAIGN_READ OMT_SUBSCRIPTION_READ GCOFFER_READ CONNECT_READ ATP_WRITE', 'jti': '7ea7ce55-1267-474b-bbf0-bf299508d8f2', 'token_type': 'bearer', 'access_token': 'gAAAAABoLfjM6_pVcAgl52nAgkonB060T2C-dVEDmrg683zxMaTbzBgP-9rJa49lYu60e_ZE0ZyAvXK_O6lPlji_Omjesp4lftTIcJVMbqlNfS3DlRRpspn7V_wVIGPQWCnPxRwvGT3AcMktP5eZgRAe_4UGV-T84U5Dtp0ThZZoUbiDYcf0a20wI_ERDSwJOo0CTtQI-tgRhuulnwtQv6gzBjH7lkIyHE--OTlz8MQdpvpeMEWOI5iAdua6bngaggCPStn4LBaXz-x1PCHjFJF368_iQ3XnE5OsppMQbsCg7lqhyrk5lt3_ep_77s60CfZSH6yUQXxr7xkJv2rEyC8-FS--cDxaE0Zkf7NRStI_g1R3rZH-ZzOai2WoPxG13FDTyFj8fHy9n1tDEMqpU9Yh-rwyTmaenZsAGN_Icq7s7U1ioYotzKH_H643K7BHRpT39Q4GEfn5zeT_UjPF2dlibMr_7yiNklvQ2qOYFRXzQTkiMfUPWlFU8GPPdj59rNX8Zavp9sL-qwBnMWCPnboPNnZ7ritsBt3xZZ_e14gy7Vql7ciVsUk4bEsLBWhNy4-L3JYdJB_nlAeeAmkJiEsCVjUHP44p9QU8Ma0NEvT7m9ZrKvL9tuSeYAgK8jrpWwxiwPrcY7qrHgAfi2ymTtcedEz5XIszYQltmTgriqY7_KQGDWciETZZKZLiUQYf0_vUh5SRsAtViX3_lNflgFV2Ioq8E1XZhgzoXhgt71iUkwHHPsb6FN810H-pPbsxQOSVm0i8j3wyOwr_gecurXXcQ4G25pHW_LBqOHUTUTcLKk7KTVIyH9gneWOKcIjFo_0PVMR2Ep6nlx2FyY_bA5WX0umAASbPHcqiOLSC4olqW1PAotoba7SQ5VBQJmQcycLqEF3tADJCR12hDAYWJHtXSzqyyYVCORcFl3DdYJqF6PB7REdNe_YXPC12nb-DztYOxncQLbR3hFJ8acxqnw9nyxTW85CYXM2_kokPFmlXWR1ELFi1EptYNiLshui80eZQkczTifnRDvxgT2PgZqBmbC__pcGWxkQ6fpGix4P_g-em7G8ZIx8hdHvKNvRHeCvD2Vmu6l2bEdGI5jbi7mxJx40JSAOrmOlW8qFeLYendBseVvmnIudEPdcKwXqOzs1Ijbx7qUB8AknQ_jlwGMV6V1O8RjOCh_jPqdMQSDAfpbpcSuVkjH45kPrBMe2hLIDy767c28cRYjfn3CusOxQVzw8rb-9U8u0iouvE-_OQ3q_q3IicY-LQI1hyaUV5_U5pOOMDVh82BP8rTEJiIayuBHLNgjXCV1ZB_YpSA0cylc7LQvhD0mkWqX0yDaqiA_9xXFFFF2fOGjRsFj08jm_AAnNQq6ipMjk7dTgSsZNc4wO9Yv_JdqZ18aXBUXtPcqY2XDXDnwrVM2HvscVSEXOkwi7qOgXuUwFXpp0U3GkqAEtazcgyF6I0E-ocanyJXLJ1qym9nU1t9mKK4uto6QNNd2ow7_L3kdBJM04eQ9giLj9pU4wcncaXM4rsBFp_2m0ktTiosf0sNIC3SE236xrdVbti5C4eMtkvjdUJppxVJgcmI5GSRdFCvILM4ejz6hLRpHgWYyWRcizZoYCPnfgZlaAEqmZQLh8bD7ZLGKKxJCKcCi7AqPXDF8f0F0TuMdbQQiLkl_hgwRZiT-qcoXhC9s6F8W0Z85NDaG0VkpNM0fPm437FdtJdY1aTqAlyAs4ABLSZO06UI3bntuJELeUfLDoU-DiST0gXOch_-YeuRHhYsaswaOyk0JAtrSEfm489-7045J2gyPKVXrzpqVmAgchi3fobUb2eDgRPBPFirW9R9PDzgGEU0uh281L-zFpAN4t3kd5FSM4B2Qn3D081zsz5vdo4YENQOWFlJoPEf6ZxuPUqoSWgZId44JHF0BO2ZVdSWJcN', 'refresh_token': 'gAAAAABoLfjMJMRpK9EkcQF9JQd6Nk2T0ROFMK6mB6g0AO1qjsMXPWeBueVG_tCaclxm3Z8d92orLndl2WakP__d_DIhImtGNFm_pZmoWK066Xj8uiUYfVinrd7bi4y3LTzfh6BGgNOo2b84ssurhOb9_IlG_gpLAb9uDikPaVGDgdej_HP2ioLeuxS9qCcjDRqc9lR0qTeo7IJJ5cVyEB3K0Rmrnnop-HrW5kTXsS9PudIRLreXXQEHHBNs4Htu_IH4Dj3t93qK693QXJhAn4SQjXNbyhMezg==', 'expires_in': 65131, 'expires_at': 1747908406, 'refresh_token_expires_in': 2591999, 'refresh_token_expires_at': 1750435274}
```

**Comment by loberhauser** [comment]
Ok here is mine:
```
Deserializing OAuth1 token. Tokens should be encrypted.
{'oauth_token': 'gAAAAABoOQYqBwKmT8HCqxWsGUPYFmREDACTED', 'oauth_token_secret': 'gAAAAABoOQYqPvepvvfWCwV6Ktr_PfPtG816eIseHy6QIVE6aHdhvbyq-Go3uY4GlTEeBug8UgSGaCnd6hhQREDACTED', 'mfa_token': 'gAAAAABoOQYqmpP26Od1S8yExIP_QWO5RxID_-UaMvvZz9sHSm35bhFytawrxREDACTED', 'mfa_expiration_timestamp': None, 'domain': 'garmin.com'}
Deserializing OAuth2 token. Tokens should be encrypted.
{'scope': 'COMMUNITY_COURSE_READ GARMINPAY_WRITE GOLF_API_READ ATP_READ GHS_SAMD GHS_UPLOAD INSIGHTS_READ DIVE_API_READ COMMUNITY_COURSE_WRITE CONNECT_WRITE GCOFFER_WRITE DI_OAUTH_2_AUTHORIZATION_CODE_CREATE GARMINPAY_READ DT_CLIENT_ANALYTICS_WRITE GOLF_API_WRITE INSIGHTS_WRITE PRODUCT_SEARCH_READ OMT_CAMPAIGN_READ OMT_SUBSCRIPTION_READ GCOFFER_READ CONNECT_READ ATP_WRITE', 'jti': 'd305abcb-ede7-4395-9REDACTED', 'token_type': 'bearer', 'access_token': 'gAAAAABoOQYqBKtdZxhLzG34gIzAFxhK2jBtOf95DDFGxIHGvRyhfXF3iW9ilhNED0rKoz0GQNWArFGBj9VrjrY3zc3hMSAMCN6SBJc7r7Q7IkxUPYZXLOyDBb9dPJK_Kf7jxp5obU5zO5n7W-Tl1cIioRtdHI7DRyZ1X8wHLrIA7dpPIyntzStZOFtjIRsq5zj2JGoWbX7AO8OvmnBaRw3b-dp6wvYjRdysOinypbF62nDsBycl-F7ep2o8cUOXDj2hd8qcIlBmaUo4lq4uUDmUtajIqynl3KkAg6OF9bZDp2ys51HcSEYwgJsLj7iuoJf-53mo6HYBMDXFKJt9fi4TFAKi9HI8tFTFszF3tEHHpSA2yAqEt3oDhNnAeg4g8-FAdRv1YiOsPNFaeeKTSjGQ5FQYLlIcPQJFNyQDokn1LC1d1mYDMcZQMqIBrcr63t3NG-jBsPeUZ9slLUDPaEJ-uj2PwaJqzSMz0iier10fIcY-8yw5K_JmMKBKnllJxdqmt5zaMuV13YP2VctA6zrU8FAmyn-GD-NhiHS-VVHbGA6gduvNWSjj3piQWYLOOdO-Y_0twV1ESv5L4umek1WYlqBIQr979zadJZWvo12AuRvCLopEp0rcjAvkKwG_wskc0p-1DEmeKqWygX5NKSYvqJhaREDACTED', 'refresh_token': 'gAAAAABoOQYq115OuX0gF01-2X3lj-P_N1A57mWEKdBs-NIc_JXY_HJ9_WbgOaENwic1vikY2aiL-PpgYzNNiwL_cEx5V-dYjx6j-1DREDACTED', 'expires_in': 104742, 'expires_at': 1748672335, 'refresh_token_expires_in': 2591999, 'refresh_token_expires_at': 1751159592}

**Comment by loberhauser** [comment]
Badly the problem still persists:
```
2025-06-02 12:26:17,390 - main_logger - ERROR - Error fetching activities for user 1 between 2025-05-26 and 2025-06-02: 'expires_in'
Traceback (most recent call last):
  File "/app/backend/garmin/activity_utils.py", line 30, in fetch_and_process_activities_by_dates
    garmin_activities = garminconnect_client.get_activities_by_date(
        start_date.date(), end_date.date()
    )
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 1151, in get_activities_by_date
    act = self.connectapi(url, params=params)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 218, in connectapi
    return self.garth.connectapi(path, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 184, in connectapi
    resp = self.request(method, "connectapi", path, api=True, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 133, in request
    self.refresh_oauth2()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 179, in refresh_oauth2
    self.oauth2_token = sso.exchange(self.oauth1_token, self)
                        ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 199, in exchange
    return OAuth2Token(**set_expirations(token))
                         ~~~~~~~~~~~~~~~^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 225, in set_expirations
    token["expires_at"] = int(time.time() + token["expires_in"])
                                            ~~~~~^^^^^^^^^^^^^^
KeyError: 'expires_in'

**Comment by matin** [comment]
@joaovitoriasilva @loberhauser looks like you didn't mask the creds in the tokens. I suggest going into the Garmin Connect dashboard and logging out of open sessions to ensure others aren't using the tokens you posted.

@loberhauser not sure what the problem could be. What you shared includes `expires_in` in the dict.

@joaovitoriasilva I try to test out different projects using Garth to see what the community is working on and how I improve Garth.

**Comment by loberhauser** [comment]
I didn't. All tokens end with "REDACTED" so only parts of the tokens are visible. Seems like they are not stored correctly.

**Comment by loberhauser** [comment]
Found the token that hasn't the `expires_in`:
`TOKEN FROM GARTH: {'message': 'org.springframework.security.oauth2.client.ClientAuthorizationException: [invalid_request] The provided MFA token was invalid', 'error': 'UnauthorizedException'}`
I got this message directly from garth in `sso.py` after line 198 (the sess.post request)
Looks like it depends on garth and not endurain @matin

**Comment by matin** [comment]
@joaovitoriasilva got it! thanks for the clarification

@loberhauser the error says the MFA code is incorrect

**Comment by matin** [comment]
I've been going through the code to see what could be causing this.

Please update to 0.5.13. https://github.com/matin/garth/pull/119 should fix the issue.

Let me know if you're still running into problems.

**Comment by matin** [comment]
Makes sense. I just created this PR for @cyberjunky: https://github.com/cyberjunky/python-garminconnect/pull/259

**Comment by loberhauser** [comment]
Badly the problem still persists even in v0.12.0 but now with a new error (snipet from app.log):
```
2025-06-09 12:42:57,521 - main_logger - ERROR - Error fetching activities for user 1 between 2025-06-02 and 2025-06-09: 403 Client Error: Forbidden for url: https://connectapi.garmin.com/oauth-service/oauth/exchange/user/2.0
Traceback (most recent call last):
  File "/app/backend/garmin/activity_utils.py", line 30, in fetch_and_process_activities_by_dates
    garmin_activities = garminconnect_client.get_activities_by_date(
        start_date.date(), end_date.date()
    )
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 1155, in get_activities_by_date
    act = self.connectapi(url, params=params)
  File "/usr/local/lib/python3.13/site-packages/garminconnect/__init__.py", line 218, in connectapi
    return self.garth.connectapi(path, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 190, in connectapi
    resp = self.request(method, "connectapi", path, api=True, **kwargs)
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 136, in request
    self.refresh_oauth2()
    ~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/garth/http.py", line 185, in refresh_oauth2
    self.oauth2_token = sso.exchange(self.oauth1_token, self)
                        ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/garth/sso.py", line 172, in exchange
    resp.raise_for_status()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://connectapi.garmin.com/oauth-service/oauth/exchange/user/2.0
```
After reconnecting to garmin it works fine until some days later. (Can't reopen the issue)

**Comment by matin** [comment]
@joaovitoriasilva looks like @Flyingfufu has it working now, but feel free to tag me again if it reoccurs

**Comment by matin** [comment]
@loberhauser ok. let me take look

**Comment by matin** [comment]
working on it now:
https://github.com/matin/garth/pull/126

**Comment by loberhauser** [comment]
Thanks @matin for the hot fix. Will test as soon as the new version of endurain is out.

**Comment by joaovitoriasilva** [comment]
@matin thanks again for the quick and awesome help.
garth is now added to poetry on [pre-release branch](https://github.com/joaovitoriasilva/endurain/commit/a47ed327e14b3a1b4f5b247038514c3d4aea405f): `garth = "^0.5.16"`

I also created a new dev version `dev_09062025` that I ask for you @loberhauser and @Flyingfufu to test and see if the issue persists. For now I will not close this issue till we get confirmation that it is fixed.

**Comment by matin** [comment]
@joaovitoriasilva found the bug:
https://github.com/joaovitoriasilva/endurain/blob/master/backend/app/core/cryptography.py#L33

`oauth1_token.mfa_token` is `None` when the user doesn't have MFA, but you cast it to a str, which is `"None"` then encrypt and decrypt `"None"`

When `garth.sso.exchange()` attempts to obtain an OAuth2 token, it passes the value `"None"` for the `mfa_token` when it should be passing `None`

Here's the PR: #196

**Comment by joaovitoriasilva** [comment]
@matin thanks again.
New dev version dev_10062025 that I ask again for you @loberhauser and @Flyingfufu to test and see if the issue persists. You need to relink Garmin and then we need to wait a few days.

**Comment by loberhauser** [comment]
Thanks @matin @joaovitoriasilva . Will test the new release right now and will respond in some days to see if the error got cleared then.

**Comment by loberhauser** [comment]
Happy to report that the bug seems to be fixed. Thanks @matin and @joaovitoriasilva for the debugging. Have a nice weekend.

**Comment by loberhauser** [comment]
@Flyingfufu I used version `dev_10062025` and reconnected to Garmin. Never had problems since.

**Comment by Flyingfufu** [comment]
> [@Flyingfufu](https://github.com/Flyingfufu) I used version `dev_10062025` and reconnected to Garmin. Never had problems since.

@loberhauser Thanks for prompt feedback. Just disconnected and reconnected and it worked. Since I'm using the latest released (and not dev) version, will track in the coming days and will report if the issue reoccur.

Thanks a lot !

**Comment by joaovitoriasilva** [comment]
Hi. Yes, relink GC is necessary like stated above.
Happy it is solved

**Comment by Flyingfufu** [comment]
Hello,

Sorry to come back with this one, but I've tried again today to download my last activity, but get thrown with some error message again. The installed version is the latest (v0.12.7).

I've tried to disconnect and reconnect my Garmin account, but same result...

```2025-07-06 13:27:59,944 - main_logger - INFO - Garmin Connect health data will be processed in the background for user 1
2025-07-06 13:27:59,946 - main_logger - INFO - User 1: Started Garmin Connect body composition processing for date range 2025-06-29 to 2025-07-06
2025-07-06 13:28:00,611 - main_logger - INFO - User 1: No new Garmin Connect body composition found between 2025-06-29 and 2025-07-06: garmin_bc is None or empty
2025-07-06 13:28:00,611 - main_logger - INFO - User 1: 0 Garmin Connect body composition processed
2025-07-06 13:34:14,139 - main_logger - INFO - Garmin Connect activities will be processed in the background for user 1
2025-07-06 13:34:15,933 - main_logger - INFO - User 1: Processing activity 19647555104
2025-07-06 13:34:16,273 - main_logger - ERROR - Error in get_user_garminconnect_activities_by_dates: [Errno 13] Permission denied: 'files/19647555104.zip'
Traceback (most recent call last):
  File "/app/backend/garmin/activity_utils.py", line 201, in get_user_garminconnect_activities_by_dates
    garminconnect_activities_processed = fetch_and_process_activities_by_dates(
        garminconnect_client, start_date, end_date, user_id, db
    )
  File "/app/backend/garmin/activity_utils.py", line 82, in fetch_and_process_activities_by_dates
    with open(output_file, "wb") as fb:
         ~~~~^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'files/19647555104.zip'
2025-07-06 13:41:57,604 - main_logger - INFO - Garmin Connect health data will be processed in the background for user 1
2025-07-06 13:41:57,609 - main_logger - INFO - User 1: Started Garmin Connect body composition processing for date range 2025-06-29 to 2025-07-06
2025-07-06 13:41:57,788 - main_logger - INFO - User 1: No new Garmin Connect body composition found between 2025-06-29 and 2025-07-06: garmin_bc is None or empty
2025-07-06 13:41:57,789 - main_logger - INFO - User 1: 0 Garmin Connect body composition processed
2025-07-06 13:42:00,288 - main_logger - INFO - Garmin Connect activities will be processed in the background for user 1
2025-07-06 13:42:00,645 - main_logger - INFO - User 1: Processing activity 19647555104
2025-07-06 13:42:01,077 - main_logger - ERROR - Error in get_user_garminconnect_activities_by_dates: [Errno 13] Permission denied: 'files/19647555104.zip'
Traceback (most recent call last):
  File "/app/backend/garmin/activity_utils.py", line 201, in get_user_garminconnect_activities_by_dates
    garminconnect_activities_processed = fetch_and_process_activities_by_dates(
        garminconnect_client, start_date, end_date, user_id, db
    )
  File "/app/backend/garmin/activity_utils.py", line 82, in fetch_and_process_activities_by_dates
    with open(output_file, "wb") as fb:
         ~~~~^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'files/19647555104.zip'
2025-07-06 13:42:34,061 - main_logger - INFO - Garmin Connect activities will be processed in the background for user 1
2025-07-06 13:42:34,410 - main_logger - INFO - User 1: Processing activity 19647555104
2025-07-06 13:42:34,779 - main_logger - ERROR - Error in get_user_garminconnect_activities_by_dates: [Errno 13] Permission denied: 'files/19647555104.zip'
Traceback (most recent call last):
  File "/app/backend/garmin/activity_utils.py", line 201, in get_user_garminconnect_activities_by_dates
    garminconnect_activities_processed = fetch_and_process_activities_by_dates(
        garminconnect_client, start_date, end_date, user_id, db
    )
  File "/app/backend/garmin/activity_utils.py", line 82, in fetch_and_process_activities_by_dates
    with open(output_file, "wb") as fb:
         ~~~~^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'files/19647555104.zip'
```

Any idea is welcome

**Comment by joaovitoriasilva** [comment]
@Flyingfufu please see issue #222

**Comment by joaovitoriasilva** [comment]
Check if the files folder has the right permissions. If you did not set GID and UID env variables, files folder should be owned by 1000:1000.

On Linux you can do:
- 'id' to check the UID:GID of your user and bellow let's assume 1000:1000 is your user
- ls -al to check who owns files folder
- if not owned by your user 
- do 'chown -R youruser:youruser <path>/folder'

Try again and it should work
