### ISSUE TITLE
[BUG]: can't access property "hr_zones_percentages"

### ISSUE THREAD

**Issue by CristianKerr** [joaovitoriasilva/endurain#221]
## Checklist

- [x] I have searched **existing issues** to make sure this bug hasn't already been reported.
- [x] I have checked the **documentation** at [https://docs.endurain.com](https://docs.endurain.com) and didn't find a solution.

## Description

I am downloading .fit files from garmin's website and then I upload them to endurain. When I open the workout detail I get this error (also screenshot below). I tried to import run/walk/hike - all of them did this. I have hr zones recorded for these workouts.

## Steps to Reproduce

1. Version v0.12.5
2. Go to Home > Add Activity
3. Upload .fit file recently downloaded from Garmin
4. Wait until import is done - new workout appears on the timeline
5. Click workout header to get to workout details
6. See error

## Expected Behavior

No error is thrown.

## Screenshots, logs or files

![Image](https://github.com/user-attachments/assets/cd473f4e-a4e6-4876-8f55-807d228c6101)

If you do not wish to upload sensitive information to the issue you can send that info to [joao@endurain.com](joao@endurain.com).

## Additional Context

Also pace is empty, but in Garmin connect I have the pace in all workouts.

**Comment by joaovitoriasilva** [comment]
Fixed on v0.12.6

**Comment by CristianKerr** [comment]
Hi I am still getting this error on v0.12.7

<img width="446" height="341" alt="Image" src="https://github.com/user-attachments/assets/3ff33fc1-a338-4445-b76f-b2dc693800c4" />

**Comment by joaovitoriasilva** [comment]
joao@endurain.com

**Comment by joaovitoriasilva** [comment]
Thanks for the feedback :)
